### ISSUE TITLE
minor roads could be lighter

### ISSUE THREAD

**Issue by mjumbewu** [laurenancona/philly-pope-map#8]
This is a total low-priority thing to try. I feel like, especially at zoom 14 and 13 (and below), the `road_minor` layer could be styled with a lighter grey. Maybe 0.5 opacity at z=14, and 0.25 opacity at z=13.

![screenshot from 2015-09-25 15 04 25](https://cloud.githubusercontent.com/assets/146749/10109750/ed40b6f8-6396-11e5-9fca-65f89e4483cd.png)
(hooray for in-browser rendering!)

**Comment by laurenancona** [comment]
Corrected in Mapbox style. I always want to address this via opacity, but with `road_*` OSM data you end up with crappy-looking nodes where lines overlap & transparency stacks up, so it has to be done via saturation/hue in color definitions.
